### ISSUE TITLE
cursor position is different between with or without this plugin when moving cursor

### ISSUE THREAD

**Issue by BTBMan** [suy/vim-context-commentstring#13]

**Comment by suy** [comment]
Please, explain exactly what you mean. Without more information, I don't understand the problem that you have.

**Comment by BTBMan** [comment]
When I use this plugin

![with1](https://user-images.githubusercontent.com/26108004/168316691-8b3d701d-b265-4d57-b2d7-f0e4843d2576.gif)

Without use

![without1](https://user-images.githubusercontent.com/26108004/168316711-3c1cccc3-c71e-4350-9741-450ab7ca4329.gif)

**Comment by suy** [comment]
I'm afraid I still don't get what's wrong. :-(

I don't know which movement should be different. I just see the cursor moving, but I don't see what's unexpected in the recording.

Note that this plugin is just checking on each cursor movement the current syntax highlighting, and based on that is changing the value of `commentstring` or `comments` (the native vim settings). That, by itself, should not change the cursor. It should be some other setting that affects where the cursor is placed.

It's very likely that is a side effect of setting those settings, to which I think I can't do anything.

If you have some way to reproduce the issue, let me know. I would need a basic setup, with some Vim or Neovim version (just in case it's affected by the shipped runtime files), and some sample Vue file. If the basic (Neo)Vim doesn't come with Vue syntax highlighting, then the plugin that you are using for such highlighting.

**Comment by BTBMan** [comment]
The cursor position is different when moving.

See, When I use plugin and I type `$` to move to end of the line, then I type `j` and `k` several times to move down/up cursor, in this moment, the cursor position of every line is same as when I did't use,

But!

When I type `b` several times to go back cursor positon from end of the line, and then I type `j` and `k` several times to move down/up cursor, the cursor position of every line is same, It's different from when I didn't use.
